latestGame = 'EXEC [dbo].[sp_LatestPlayerApps]'
teamRosters = 'EXEC [dbo].[sp_TeamRosters]'
teams = 'SELECT * FROM [dbo].[vwTeams]'
shotChart = 'EXEC [dbo].[sp_PlayerShotChart]'
standings = 'SELECT * FROM [dbo].[vwStandings]'
