latest_game_query = 'EXEC [dbo].[sp_LatestPlayerApps]'
team_roster_query = 'EXEC [dbo].[sp_TeamRosters]'
team_query = 'SELECT * FROM [dbo].[vwTeams]'
shot_chart_query = 'EXEC [dbo].[sp_PlayerShotChart]'
standings_query = 'SELECT * FROM [dbo].[vwStandings]'
team_game_stats_query = 'EXEC [dbo].[sp_TeamGameStats]'
team_season_stats_query = 'EXEC [dbo].[sp_TeamSeasonStats]'
